
export const villas = [
  {
    id: 1,
    name: "Dam Villa",
    location: "Syria",
    category: "Damascus",
    guests: 4,
    bedrooms: 8,
    bathrooms: 4,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa1.jpg",
    price: "8,000,000,000 S.P",
  },
  {
    id: 2,
    name: "T Hut",
    location: "Syria",
    category: "Lattakia",
    guests: 8,
    bedrooms: 8,
    bathrooms: 12,
    squareMeter: "450",
    rating: 4.8,
    image: "/villa2.jpg",
    price: "2,500,000,000 S.P",
  },
  {
    id: 3,
    name: "Shop",
    location: "Syria",
    category: "Mazzzeh",
    guests: 1,
    bedrooms: 0,
    bathrooms: 1,
    squareMeter: "90",
    rating: 4.9,
    image: "/villa3.jpg",
    price: "1,600,000,000 S.P",
  },
  {
    id: 4,
    name: "Mountain Farm",
    location: "Syria",
    category: "Zabadani",
    guests: 8,
    bedrooms: 15,
    bathrooms: 7,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    price: "26,000,000,000 S.P",
  },
  {
    id: 5,
    name: "Ahmad's Villa",
    location: "Syria",
    category: "Sabboura",
    guests: 4,
    bedrooms: 5,
    bathrooms: 6,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    price: "950,000,000 S.P",
  },
  {
    id: 6,
    name: "Heavenous",
    location: "Syria",
    category: "Tartus",
    guests: 12,
    bedrooms: 14,
    bathrooms: 6,
    squareMeter: "900",
    rating: 4.9,
    image: "/villa6.jpg",
    price: "35,000,000,000 S.P",
  },
  {
    id: 7,
    name: "Abo Ali's Hut",
    location: "Syria",
    category: "Lattakia",
    guests: 1,
    bedrooms: 0,
    bathrooms: 1,
    squareMeter: "75",
    rating: 4.8,
    image: "/villa7.jpg",
    price: "200,000,000 S.P",
  },
  {
    id: 8,
    name: "Hope Coffee Shop",
    location: "Syria",
    category: "Mazr3a",
    guests: 2,
    bedrooms: 0,
    bathrooms: 1,
    squareMeter: "140",
    rating: 5.0,
    image: "/villa8.jpg",
    price: "600,000,000 S.P",
  },
  {
    id: 9,
    name: "Theaa",
    location: "Syria",
    category: "Tartus",
    guests: 5,
    bedrooms: 6,
    bathrooms: 4,
    squareMeter: "240",
    rating: 4.2,
    image: "/villa9.jpg",
    price: "1,400,000,000 S.P",
  },
];

